### ISSUE TITLE
Update readme since `WritableStream`s seem supported now

### ISSUE THREAD

**Issue by dario-piotrowicz** [marko-js/writable-dom#3]
### Description

Hey @DylanPiercey just wanted to say that I think that `WritableStream`s are now supported across the board (by firefox since May according to [caniuse](https://caniuse.com/mdn-api_writablestream_writablestream)).

So I guess the Readme could be updated to present only the shorter syntax 🙂 

And the code could actually be cleaned up to use directly a class instead of a constructor function I'd imagine?

If you're interested let me know as I'd gladly make the changes 😄

**Comment by DylanPiercey** [comment]
I think updating the readme would be good. However I'd still like to show both examples and keep the underlying impl as is for best browser support.

**Comment by dario-piotrowicz** [comment]
Ok, just updating the readme then! I gave it a shot please have a look :slightly_smiling_face:
