### ISSUE TITLE
Error: Dynamic require of "path/to/marko.file" is not supported

### ISSUE THREAD

**Issue by ghost** [marko-js/writable-dom#8]
ver. 1.0.3

Following the example code from the repo page.

I get an Error: Dynamic require of  "path/to/marko.file" is not supported.

But if the ""path/to/marko.file"  is initially imported somewhere in the layout marko template before the fetch call/event.  Then the fetch response would work ("path/to/marko.file").  Mind you,  the html string will still be sent/parse and recieved but not the functionality. e.g. "class {onClick(){blah..blah..}

I'm curious as to how to actually use this or I did something wrong?

Thanks!

**Comment by mikko-severo** [comment]
Closing this.  I think The issue has nothing to do with the this library.  It could stem from vite.

**Comment by ghost** [comment]
Closing this.  I think The issue has nothing to do with the this library.  It could stem from vite.
